# top level stuff you probably don't need to touch
#highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true
url: http://matthewdowney.github.io/
#baseurl: /
title: Matthew Downey
author: Matthew Downey
description: Personal blog and resume
avatar: profile.jpg
email: matthewdowney20@gmail.com
github: matthewdowney
instagram: _matthewdowney
disqus: matthewdowney
google_analytics: UA-69391421-1

# needed for travis-ci build
exclude: [vendor]

# syntax highlighting
syntax-highlighting:
    enabled : true
    css: syntax.css
    #css: solarized-light.css

