# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: http://matthewdowney.github.io/
baseurl: /sustain/
title: Matthew Downey
author: Matthew Downey
description: Personal blog and resume
avatar: profile.jpg
email: matthewdowney20@gmail.com
github: matthewdowney/matthewdowney.github.io # username
#Comment out if you don't want disqus 
disqus: username
google_analytics: UA-69391421-1

# needed for travis-ci build
exclude: [vendor]
