# top level stuff you probably don't need to touch
highlighter: pygments
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems:
  - jekyll-paginate
  - jekyll-feed
port: 3000
safe: true
url: https://matthewdowney.github.io
#baseurl: /
title: Matthew Downey
author: Matthew Downey
description: Finance, cryptography, and software (mostly Clojure currently).
avatar: profile.jpg
email: mjdowney@protonmail.ch
github: matthewdowney
instagram: _matthewdowney
disqus: matthewdowney-github-io

# needed for travis-ci build
exclude: [vendor]

# syntax highlighting
syntax-highlighting:
    enabled : true
    css: syntax.css
    #css: solarized-light.css

plugins_dir:
  - jekyll-seo-tag
  - jekyll-feed
